"""Export the deterministic API contract generated by the FastAPI app."""

import json
import os
from pathlib import Path
import sys

os.environ.setdefault("SUPERTOKENS_ENABLED", "false")
os.environ.setdefault("REQUEST_REPOSITORY", "memory")
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.main import app  # noqa: E402


def main() -> None:
    destination = Path(__file__).resolve().parents[1] / "docs" / "openapi.json"
    destination.write_text(
        json.dumps(app.openapi(), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(destination)


if __name__ == "__main__":
    main()
